backend:
  name: github
  repo: hoshimov-iqtisod/hoshimov-blog

media_folder: static/assets
public_folder: assets

collections:
  - label: Blog in English
    name: english_posts
    folder: blog/en
    create: true
    filter: { field: "language", value: "en" }
    identifier_field: name
    fields:
      - { name: language, label: "Language", widget: "select", options: ["en", "ru", "uz"] }
      - { name: title, label: Title, widget: string }
      - { name: name, label: Name, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: video_url, label: VideoUrl, widget: string }
      - { name: audio, label: Audio, widget: file }
      - { name: body, label: Body, widget: markdown }

  - label: Blog in Russian
    name: russian_posts
    folder: blog/ru
    create: true
    filter: { field: "language", value: "ru" }
    identifier_field: name 
    fields:
      - { name: language, label: "Language", widget: "select", options: ["en", "ru", "uz"] }
      - { name: title, label: Title_RU, widget: string }
      - { name: name, label: Name, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: video_url, label: VideoUrl, widget: string }
      - { name: audio, label: Audio, widget: file }
      - { name: body, label: Body_RU, widget: markdown }

  - label: Blog in Uzbek
    name: uzbek_posts
    folder: blog/uz
    create: true
    filter: { field: "language", value: "uz" }
    identifier_field: name
    fields:
      - { name: language, label: "Language", widget: "select", options: ["en", "ru", "uz"] }
      - { name: title, label: Title_UZ, widget: string }
      - { name: name, label: Name, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: video_url, label: VideoUrl, widget: string }
      - { name: audio, label: Audio, widget: file }
      - { name: body, label: Body_UZ, widget: markdown }
