backend:
  name: github
  repo: oripovd1/hoshimov-blog

media_folder: static/assets
public_folder: assets

collections:
  - label: Blog in English
    name: english_posts
    folder: blog
    create: true
    filter: { field: "language", value: "en" }
    fields:
      - { name: language, label: "Language", widget: "select", options: ["en", "ru"] }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }

  - label: Blog in Russian
    name: russian_posts
    folder: blog
    create: true
    filter: { field: "language", value: "ru" }
    fields:
      - { name: language, label: "Language", widget: "select", options: ["en", "ru"] }
      - { name: title, label: Title_RU, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body_RU, widget: markdown }

  - label: Blog in Uzbek
    name: uzbek_posts
    folder: blog
    create: true
    filter: { field: "language", value: "uz" }
    fields:
      - { name: language, label: "Language", widget: "select", options: ["en", "ru", "uz"] }
      - { name: title, label: Title_UZ, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body_UZ, widget: markdown }

